spring:
  application:
    name: redis-cache-benchmark

  datasource:
    url: jdbc:postgresql://localhost:5433/redisbench
    username: redisbench
    password: redisbench
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 20
      minimum-idle: 5
      connection-timeout: 30000

  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc:
          batch_size: 1000
          order_inserts: true
          order_updates: true
        format_sql: false
    open-in-view: false
    show-sql: false

  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration

  data:
    redis:
      host: localhost
      port: 6380
      timeout: 2000ms

  cache:
    type: redis
    redis:
      time-to-live: 600000   # 10 dk default TTL
      cache-null-values: false

server:
  port: 8080

logging:
  level:
    org.hibernate.SQL: warn
    org.springframework.cache: info

app:
  seed:
    enabled: true
    products: 200000
    categories: 50
    brands: 200
    batch-size: 1000
